name: mofud
description: food delivery app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  colorful_safe_area: ^0.2.0
  cached_network_image: ^2.2.0
  dio: ^3.0.10
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.2.3
  connectivity: ^0.4.9
  hive: ^1.4.3
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  hive_generator: ^0.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
